services:
  postgres:
    image: postgres@sha256:fe45ed1a824b81c0c9c605890963b67501758ca8c946db89089c85ce0f88e974
    container_name: interstellar-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: interstellar-route-planner-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    ports:
      - "8000:8000"
    command: >
      sh -c "
        echo '⏳ Waiting for PostgreSQL to be ready...';
        until pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER}; do
          echo '⏳ Waiting...';
          sleep 5;
        done;
        echo '✅ DB is ready. Running migrations...';
        [ -d migrations ] && npx knex migrate:latest;
        echo '🚀 Starting API server...';
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  prometheus:
    image: prom/prometheus
    container_name: interstellar-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data: