services:
  postgres:
    image: postgres:15
    container_name: interstellar-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: London25
      POSTGRES_DB: interstellar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://myuser:London25@postgres:5432/interstellar_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: