apiVersion: v1
kind: Service
metadata:
  name: interstellar-service
  namespace: interstellar
spec:
  type: LoadBalancer
  selector:
    app: interstellar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000