apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: interstellar
spec:
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432