jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # <-- Add this line to install pytest

      - name: Run tests
        run: pytest test_api.py  # <-- Now pytest should work

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ad4johnson/interstellar-route-planner:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f postgres-deployment.yaml
          kubectl apply -f interstellar-service.yaml