name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests  # ✅ Ensure 'requests' is installed

      - name: Debug Directory Contents
        run: ls -R  # List all files to verify test file location

      - name: Run tests
        run: pytest tests/test_api.py  # Ensure correct test path

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'"
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "❌ DOCKER_PASSWORD is EMPTY!"
            exit 1
          else
            echo "✅ DOCKER_PASSWORD is SET."
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ad4johnson/interstellar-route-planner:latest

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'  # Ensures latest kubectl version

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f postgres-deployment.yaml
          kubectl apply -f postgres-service.yaml
          kubectl apply -f interstellar-service.yaml